# Generated by Django 4.2.26 on 2026-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_password', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
