# Generated by Django 4.2.26 on 2026-06-17 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
