# Generated by Django 4.2.26 on 2026-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_serviceentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='staffpermission',
            name='permission',
            field=models.CharField(choices=[('edit_records', 'Edit Records')], max_length=50),
        ),
    ]
