# Generated by Django 4.2.26 on 2026-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_profile_photo_alter_staffpermission_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji or icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='')),
                ('hours', models.CharField(blank=True, default='', max_length=200)),
                ('holiday', models.CharField(blank=True, default='', max_length=200)),
                ('shop_name', models.CharField(blank=True, default='VINO Browsing Center', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('hero_title', models.CharField(blank=True, default='', max_length=300)),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_service_tags', models.TextField(blank=True, default='', help_text='Comma-separated service tags for hero section')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('map_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
