# Generated by Django 4.2.26 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobupdate_publicservice_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobupdate',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='jobupdate',
            name='date',
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
