# Generated by Django 4.2.26 on 2026-06-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobupdate_options_remove_jobupdate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_date', '-created_at'],
            },
        ),
    ]
