# Generated by Django 4.2.26 on 2026-06-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_educationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobupdate',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='exam_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='post_count',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobupdate',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
