# Generated by Django 4.2.26 on 2026-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobupdate_exam_date_jobupdate_exam_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='community_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
