# Generated by Django 4.2.26 on 2026-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sitesettings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
