# Generated by Django 4.2.26 on 2026-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
