# Generated by Django 4.2.26 on 2026-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationapplication',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='educationapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education/'),
        ),
        migrations.AddField(
            model_name='educationapplication',
            name='post_count',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='educationapplication',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='educationapplication',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
