# Generated by Django 4.2.17 on 2026-07-01 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_educationapplication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='attendance_late_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Staff arriving after this time are marked as Late'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='attendance_working_days',
            field=models.CharField(default='1,2,3,4,5,6', help_text='Comma separated days (0=Sunday, 1=Monday, ... 6=Saturday)', max_length=50),
        ),
    ]
