# Generated by Django 4.2.17 on 2026-07-10 08:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemsettings_attendance_late_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='core.serviceentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
