# Generated by Django 4.2.17 on 2026-07-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customer_deleted_at_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='pan_card_charge',
            field=models.DecimalField(decimal_places=2, default=107.0, help_text='Default charge amount for PAN card services', max_digits=10),
        ),
    ]
